### PR TITLE
Flicker remove

### PR DESCRIPTION
**Pull request by arnav127**
This pull request resolves screen flicker issue #3 . Instead of clearing the screen, now the cursor goes to (0, 0) and it overwrites, this is faster than clearing the screen and then writing and it produces smoother experience. The commit d28c8b4 changed the controls to awsd but this has been reverted back to the original controls of atbl, as this is user's choice.

### CODE REVIEW

**Comment by kivi3004** [comment]
I don't understand where u changed to remove flicker.

**Comment by arnav127** [comment]
Instead of clearing the screen, the prompt is moved to the location (0,0) or the starting of the screen by the line `printf("\033[0;0H");`

**Comment by kivi3004** [comment]
I checked it but it(printf("\033[0;0H");) not responding as you say in c++(printf("\033[0;0H");

**Comment by arnav127** [comment]
ezgif-1-97c10b78a1fd


I have tried this on both Windows and Linux and it works smoothly, here is the video of the program running on Windows and Linux

**Comment by kivi3004** [comment]
Ok, Thank you for correcting me

**Pull request closed without merging**
